version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    working_dir: /app
    env_file:
      - ./app/.env
    environment:
      - HOST=0.0.0.0
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "81:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared

volumes:
  mysql_data:
